# ServiceAccount for troubleshooting tools pod
apiVersion: v1
kind: ServiceAccount
metadata:
  name: troubleshooting-sa
---
# RoleBinding to grant the ServiceAccount access to the privileged SCC
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: troubleshooting-sa-privileged-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
  - kind: ServiceAccount
    name: troubleshooting-sa
---
# Deployment for the troubleshooting tools container
apiVersion: apps/v1
kind: Deployment
metadata:
  name: troubleshooting-tools
spec:
  replicas: 1  # Only one pod needed for troubleshooting
  selector:
    matchLabels:
      app: troubleshooting-tools
  template:
    metadata:
      labels:
        app: troubleshooting-tools
    spec:
      serviceAccountName: troubleshooting-sa  # Use the above ServiceAccount
      containers:
        - name: troubleshooting-tools
          image: docker.io/moosestack/troubleshooting-tools:latest  # Use the latest built image
          securityContext:
            # Required for some network tools and if you want to install more packages with dnf
            privileged: true 
            runAsUser: 0
            allowPrivilegeEscalation: true
          resources:
            requests:
              memory: "128Mi"  # Minimum memory guaranteed
              cpu: ".3"        # Minimum CPU guaranteed
            limits:
              memory: "512Mi"  # Maximum memory allowed
              cpu: "1"         # Maximum CPU allowed
