name: Troubleshooting Tools Container Build and Push

on:
  push:
    branches:
      - main
    paths:
      - Containerfile
      - .github/workflows/image-build-push.yaml
  schedule:
    - cron: '0 0 1 * *'  # Runs at 00:00 on the 1st of every month

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get date for tag
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Containerfile
          push: true
          tags: |
            moosestack/troubleshooting-tools:latest
            moosestack/troubleshooting-tools:fedora-${{ steps.date.outputs.date }}